import { readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { publint } from 'publint';
import { formatMessage } from 'publint/utils';

const packagePath = resolve('package.json');
const packageBackupPath = resolve('package.json-prepack');
const generatedFiles = [resolve('config.schema.json'), packageBackupPath];
const backstageGeneratedFindings = new Set([
  'EXPORTS_VALUE_INVALID:exports...backstage',
]);

process.env.npm_config_cache = join(tmpdir(), 'publint-npm-cache');

/**
 * Produces a stable identifier for a Publint finding.
 *
 * @param {import('publint').Message} message - Structured Publint finding.
 * @returns {string} Finding code combined with its package path.
 */
function findingKey(message) {
  return `${message.code}:${message.path.join('.')}`;
}

/**
 * Reports one Publint finding and identifies whether it is an error.
 *
 * @param {import('publint').Message} message - Finding to report.
 * @param {Record<string, any>} pkg - Transformed package manifest.
 * @returns {boolean} `true` when the finding must fail validation.
 * @remarks The known Backstage feature-marker finding is reported and ignored.
 */
function reportMessage(message, pkg) {
  const formatted = formatMessage(message, pkg);
  if (backstageGeneratedFindings.has(findingKey(message))) {
    console.warn(`Ignoring Backstage-generated Publint finding: ${formatted}`);
    return false;
  }

  const output = message.type === 'error' ? console.error : console.warn;
  output(formatted);
  return message.type === 'error';
}

/**
 * Reports all Publint findings and resolves their aggregate exit code.
 *
 * @param {import('publint').Message[]} messages - Findings to report.
 * @param {Record<string, any>} pkg - Transformed package manifest.
 * @returns {number} Process exit code: `1` for errors, otherwise `0`.
 */
function reportMessages(messages, pkg) {
  let exitCode = 0;
  for (const message of messages) {
    if (reportMessage(message, pkg)) {
      exitCode = 1;
    }
  }
  return exitCode;
}

/**
 * Removes files generated by Backstage prepack.
 *
 * @returns {void}
 * @remarks Missing files are ignored, making cleanup idempotent.
 */
function removeGeneratedFiles() {
  for (const generatedFile of generatedFiles) {
    rmSync(generatedFile, { force: true });
  }
}

/**
 * Restores the development manifest and removes prepack-generated files.
 *
 * @param {string} originalPackage - Original package manifest contents.
 * @returns {void}
 * @remarks Restoration is idempotent and also covers failed npm lifecycles.
 */
function restorePackage(originalPackage) {
  writeFileSync(packagePath, originalPackage);
  removeGeneratedFiles();
}

/**
 * Validates the Backstage-transformed npm package with Publint.
 *
 * @returns {Promise<number>} Process exit code for package validation.
 * @remarks Always restores the development manifest and generated files.
 */
async function validatePackage() {
  const originalPackage = readFileSync(packagePath, 'utf8');
  let exitCode = 0;
  try {
    const result = await publint({ pack: 'npm' });
    exitCode = reportMessages(result.messages, result.pkg);
  } catch (error) {
    console.error(error);
    exitCode = 1;
  } finally {
    restorePackage(originalPackage);
  }
  return exitCode;
}

process.exitCode = await validatePackage();
